# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=4, null=True)),
                ('nama', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jurusan',
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, null=True)),
                ('mapel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolahapp.Jurusan')),
            ],
            options={
                'verbose_name_plural': 'Mata Pelajaran',
            },
        ),
    ]
