# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sekolahapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(db_index=True, max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100, null=True)),
                ('mapel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolahapp.MataPelajaran')),
            ],
            options={
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(db_index=True, max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100, null=True)),
                ('kelas', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1)),
                ('jurusan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolahapp.Jurusan')),
                ('mapel', models.ManyToManyField(null=True, to='sekolahapp.MataPelajaran')),
            ],
            options={
                'verbose_name_plural': 'Siswa',
            },
        ),
    ]
