# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='mapel',
            field=models.ManyToManyField(to='sekolahapp.MataPelajaran'),
        ),
    ]
