# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sekolahapp', '0003_auto_20170830_0406'),
        ('userapp', '0003_auto_20170830_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='mapel',
        ),
        migrations.AddField(
            model_name='siswa',
            name='mapel',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='jurusan', null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolahapp.MataPelajaran'),
        ),
    ]
